name: SoldinRegister
version: 5.1.0
main: com.soldinregister.SoldinRegister
api-version: '1.20'
author: Soldi_n
website: https://example.com
commands:
  register:
    description: Register an account
    aliases: [reg]
    usage: "/register <password>"
  login:
    description: Login to your account
    aliases: [l]
    usage: "/login <password> [2faCode]"
  changepass:
    description: Change your password
    usage: "/changepass <old> <new>"
  twofa:
    description: 2FA operations (enable/confirm/disable/unbind/url)
    usage: "/twofa <enable|confirm|disable|unbind|url> [code|password]"
  soldinregister:
    description: Admin commands
    aliases: [sreg, sregister]
    usage: "/soldinregister <reload|changepass|delete|reset2fa> ..."
permissions:
  soldinregister.admin:
    default: op
  soldinregister.bypass:
    default: op
