
name: SoldinRegister
version: 6.0.0
main: com.soldinregister.SoldinRegister
api-version: 1.20
author: Soldi_n
website: https://example.com
commands:
  register:
    description: Регистрация
    aliases: [reg]
    usage: "/register <пароль>"
    permission: soldinregister.user
  login:
    description: Логин
    aliases: [l]
    usage: "/login <пароль> [код2FA]"
    permission: soldinregister.user
  changepass:
    description: Смена пароля
    usage: "/changepass <старый> <новый>"
    permission: soldinregister.user
  twofa:
    description: Управление 2FA
    usage: "/twofa <enable|confirm|disable|unbind|url> [код]"
    permission: soldinregister.user
  soldinregister:
    description: Админ-команды
    usage: "/soldinregister <reload|changepass <ник> <новый> | delete <ник> | reset2fa <ник>>"
    permission: soldinregister.admin
permissions:
  soldinregister.user:
    default: true
  soldinregister.admin:
    default: op
