name: SoldinRegister
main: com.soldinregister.SoldinRegister
version: 5.0.0
api-version: '1.16'
author: Soldi_n .jar
commands:
  register:
    description: Регистрация
    aliases: [reg]
  login:
    description: Вход
    aliases: [l]
  changepass:
    description: Сменить пароль
  2fa:
    description: Управление двухфакторной аутентификацией
  soldinregister:
    description: Админ команды SoldinRegister
    permission: soldinregister.admin
permissions:
  soldinregister.admin:
    description: Доступ к админ-командам SoldinRegister
    default: op
