name: Build SoldinRegister

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package

      - name: Upload Plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: SoldinRegister
          path: target/*.jar
